name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x86

      - name: checkout
        uses: actions/checkout@v2

      - name: download-openjtalk
        run: |
          dir
          Invoke-Webrequest -Uri https://jaist.dl.sourceforge.net/project/open-jtalk/Open%20JTalk/open_jtalk-1.11/open_jtalk-1.11.tar.gz -OutFile open_jtalk-1.11.tar.gz
          dir

      - name: extract
        run: |
          dir
          7z x -tgzip -so open_jtalk-1.11.tar.gz | 7z x -si -ttar
          dir

      - name: build
        run: |
          msbuild -version
