name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x86

      - name: checkout
        uses: actions/checkout@v2

      - name: log0
        run: dir

      - name: download-openjtalk
        run: Invoke-Webrequest http://downloads.sourceforge.net/open-jtalk/open_jtalk-1.11.tar.gz -OutFile open_jtalk-1.11.tar.gz

      - name: log1
        run: dir

      - name: extract
        run: 7z x -tgzip -so open_jtalk-1.11.tar.gz | 7z x -si -ttar

      - name: log2
        run: dir

      - name: build
        run: |
          pushd open_jtalk-1.11
          nmake -f Makefile.mak
          popd

      - name: log2
        run: dir
