name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: download-openjtalk
        run: Invoke-Webrequest http://downloads.sourceforge.net/open-jtalk/open_jtalk-1.11.tar.gz

      - name: extract
        run: 7z xvf open_jtalk-1.11.tar.gz

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x86

      - name: build
        run:
          pushd open_jtalk-1.11
          nmake -f Makefile.mak
          popd
